# Generated by Django 3.2.5 on 2021-07-29 22:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BldgNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('GPSCoor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128, unique=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.college')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3, "Minimum Length of a device's name is 3 letters")])),
                ('PPM_Cycle', models.IntegerField(blank=True, default=180, null=True)),
                ('Brief_Function_Description', models.TextField(max_length=300)),
                ('accessories', models.ManyToManyField(to='inventory.Accessory')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceMaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('Biomedical', 'Biomedical'), ('Electrical', 'Electrical'), ('Electronic', 'Electronic'), ('Mechanical', 'Mechanical'), ('Electromechanical', 'Electromechanical')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('Operational', 'Operational'), ('Malfunctioning', 'Malfunctioning')], max_length=50, unique=True)),
                ('Condition', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(choices=[('60', 60), ('50', 50), ('60/50', '60/50'), ('DC', 'DC')], max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(choices=[('Single Phase', 'Single Phase'), ('Three phase', 'Three phase'), ('DC', 'DC')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, "Minimum Length of a Model's name is 3 letters")])),
                ('Voltage', models.DecimalField(decimal_places=3, max_digits=8)),
                ('Amperage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.device')),
                ('frequency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.frequency')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.manufacturer')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.phase')),
            ],
        ),
        migrations.CreateModel(
            name='LabRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('FloorNo', models.IntegerField()),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department')),
                ('Operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('blgdno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.bldgno')),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.campus')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAsset',
            fields=[
                ('Asset_No', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('Serial_Number', models.CharField(max_length=50)),
                ('DevicePic', models.FileField(upload_to='', verbose_name='Devices/pictures/')),
                ('DownTime', models.DateTimeField(blank=True, null=True)),
                ('DeviceStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.devicestatus')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.labroom')),
                ('warranty', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.warranty')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='deviceclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.deviceclass'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='accmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.accmodel'),
        ),
        migrations.CreateModel(
            name='AccDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=500)),
                ('SerialNo', models.CharField(max_length=50, unique=True)),
                ('accessory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.accessory')),
            ],
        ),
    ]
