# Generated by Django 3.2.5 on 2021-08-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['Name']},
        ),
        migrations.AlterField(
            model_name='device',
            name='accessories',
            field=models.ManyToManyField(blank=True, to='inventory.Accessory'),
        ),
    ]
