# Generated by Django 3.2.5 on 2021-08-03 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210803_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='device_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.device'),
        ),
        migrations.AddField(
            model_name='model',
            name='device_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.device'),
        ),
        migrations.AddField(
            model_name='model',
            name='phase_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.phase'),
        ),
        migrations.AddField(
            model_name='model',
            name='phase_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.phase'),
        ),
    ]
