# Generated by Django 3.2.5 on 2021-07-26 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_manufacturer_agentcompanies'),
        ('inventory', '0002_alter_accdetails_accessory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='College',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='model',
            name='spareParts',
        ),
        migrations.AlterField(
            model_name='model',
            name='amperage',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='model',
            name='frequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='model',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.manufacturer'),
        ),
        migrations.AlterField(
            model_name='model',
            name='voltage',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
