# Generated by Django 3.2.5 on 2021-08-03 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210803_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Brief_Function_Description_ar',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='Brief_Function_Description_en',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='Name_ar',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3, "Minimum Length of a device's name is 3 letters")]),
        ),
        migrations.AddField(
            model_name='device',
            name='Name_en',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3, "Minimum Length of a device's name is 3 letters")]),
        ),
        migrations.AlterField(
            model_name='phase',
            name='Value',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='Value_ar',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='Value_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
