# Generated by Django 3.2.5 on 2021-08-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210803_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='Amperage',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='model',
            name='Voltage',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
