# Generated by Django 3.2.5 on 2021-08-05 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210804_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accdetails',
            name='Description',
        ),
        migrations.AddField(
            model_name='accessory',
            name='Description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accdetails',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.accessory'),
        ),
    ]
