# Generated by Django 3.2.5 on 2021-08-06 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210805_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='accmodel',
        ),
        migrations.AddField(
            model_name='accmodel',
            name='accessory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.accessory'),
        ),
    ]
