# Generated by Django 3.2.5 on 2021-08-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210806_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='Name_ar',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='Name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
