# Generated by Django 3.2.5 on 2021-08-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210806_0840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccDetails',
            new_name='AccDetail',
        ),
    ]
