# Generated by Django 3.2.5 on 2021-08-07 04:34

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_accdetails_accdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='accdetail',
            name='accmodel',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='accessory', chained_model_field='accessory', default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.accmodel'),
            preserve_default=False,
        ),
    ]
