# Generated by Django 3.2.5 on 2021-08-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_accdetail_accmodel'),
        ('inventory', '0013_auto_20210808_0814'),
    ]

    operations = [
    ]
