# Generated by Django 3.2.6 on 2021-08-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_name_department_deptname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='deptName',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
    ]
