# Generated by Django 3.2.5 on 2021-07-29 22:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('Engineer', 'Engineer'), ('Technician', 'Technician'), ('Labor', 'Labor'), ('Administrator', 'Administrator')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('National_ID', models.BigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000, 'Please Enter 10 Numbers.'), django.core.validators.MaxValueValidator(9999999999, 'Please Enter Less than 10 Numbers.')])),
                ('Name', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(4, 'Name Must be 4 characters.')])),
                ('DoB', models.DateField(blank=True, null=True)),
                ('PassportNo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ExpSCE', models.DateField(blank=True, null=True)),
                ('ExpID', models.DateField(blank=True, null=True)),
                ('ExpPassport', models.DateField(blank=True, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('Experience', models.IntegerField()),
                ('MobileNo', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(500000000, 'Please Enter 10 Numbers.'), django.core.validators.MaxValueValidator(599999999, 'Please Enter Less than 10 Numbers.')])),
                ('Salary', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Lapses', models.IntegerField(blank=True, null=True)),
                ('Warnings', models.IntegerField(blank=True, null=True)),
                ('ID_PDF', models.FileField(blank=True, null=True, upload_to='employees/id/')),
                ('Cert_PDF', models.FileField(blank=True, null=True, upload_to='employees/Certs/')),
                ('CV_PDF', models.FileField(blank=True, null=True, upload_to='employees/CVs/')),
                ('Contract_PDF', models.FileField(blank=True, null=True, upload_to='employees/Contracts/')),
                ('Effective_PDF', models.FileField(blank=True, null=True, upload_to='employees/Effectives/')),
                ('Passport_PDF', models.FileField(blank=True, null=True, upload_to='employees/Passports/')),
                ('SCE_PDF', models.FileField(blank=True, null=True, upload_to='employees/SCEs/')),
                ('Experience_PDF', models.FileField(blank=True, null=True, upload_to='employees/Experiences/')),
                ('UserRole', models.IntegerField(choices=[(1, 'Sorouh Employee'), (2, 'Taif University Employee'), (3, 'Lab Operator'), (4, 'Foreign Employee')], default=1)),
                ('Reason', models.TextField(blank=True, max_length=500, null=True)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jobtitle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.jobtitle')),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('Saudi', 'Saudi'), ('Egyptian', 'Egyptian'), ('Sudanese', 'Sudanese'), ('Indian', 'Indian'), ('Pakistani', 'Pakistani')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrikeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4, 'Tool minimum length is 4 characters')])),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleType', models.CharField(choices=[('Sedan', 'Sedan'), ('Truck', 'Truck')], default='Sedan', max_length=50)),
                ('Manufacturer', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('YearMake', models.IntegerField()),
                ('Plate', models.CharField(max_length=50)),
                ('ExpRegistration', models.DateField()),
                ('ExpInsurance', models.DateField()),
                ('ExpInspection', models.DateField()),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.member')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QTY', models.IntegerField(default=1)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.member')),
                ('tooltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.tooltype')),
            ],
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(blank=True, null=True)),
                ('StrikePic', models.FileField(upload_to='strikes/%Y/%m/%d/')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.member')),
                ('strikedetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.strikedetail')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.nationality'),
        ),
        migrations.CreateModel(
            name='LocationsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InTime', models.DateTimeField(auto_now_add=True)),
                ('OutTime', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.labroom')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.member')),
            ],
        ),
    ]
