# Generated by Django 3.2.5 on 2021-07-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('National_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('DoB', models.DateField(default=None)),
                ('PassportNo', models.IntegerField(unique=True)),
                ('ExpSCE', models.DateField(default=None)),
                ('ExpID', models.DateField(default=None)),
                ('ExpPassPort', models.DateField(default=None)),
                ('Qualification', models.TextField(max_length=500)),
                ('Title', models.CharField(max_length=100)),
                ('Experience', models.TextField(max_length=500)),
                ('MobileNo', models.IntegerField(unique=True)),
                ('Nationality', models.CharField(max_length=50)),
                ('Salary', models.IntegerField()),
                ('Lapses', models.IntegerField(default=None)),
                ('Warnings', models.CharField(max_length=200)),
                ('ID_PDF', models.FileField(upload_to='')),
                ('Cert_PDF', models.FileField(upload_to='')),
                ('CV_PDF', models.FileField(upload_to='')),
                ('Contract_PDF', models.FileField(upload_to='')),
                ('Effective_PDF', models.FileField(upload_to='')),
                ('Passport_PDF', models.FileField(default=None, upload_to='')),
                ('SCE_PDF', models.FileField(default=None, upload_to='')),
                ('Experience_PDF', models.FileField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StrikeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleType', models.CharField(max_length=50)),
                ('Manufacturer', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('YearMake', models.IntegerField()),
                ('Plate', models.CharField(max_length=50)),
                ('ExpRegistration', models.DateField()),
                ('ExpInsurance', models.DateField()),
                ('ExpInspection', models.DateField()),
                ('Member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.member')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QTY', models.IntegerField(default=0)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.member')),
                ('ToolType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.tooltype')),
            ],
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateField(default=None)),
                ('StrikePic', models.FileField(default=None, upload_to='')),
                ('Member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.member')),
                ('StrikeDetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.strikedetail')),
            ],
        ),
        migrations.CreateModel(
            name='LocationsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InTime', models.DateTimeField(auto_now_add=True)),
                ('OutTime', models.DateTimeField(auto_now_add=True)),
                ('Lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.labroom')),
                ('Member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.member')),
            ],
        ),
    ]
