# Generated by Django 3.2.5 on 2021-07-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
