# Generated by Django 3.2.5 on 2021-07-28 18:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='Member',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='strike',
            name='Member',
        ),
        migrations.RemoveField(
            model_name='strike',
            name='StrikeDetail',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='ToolType',
        ),
        migrations.AddField(
            model_name='strike',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.member'),
        ),
        migrations.AddField(
            model_name='strike',
            name='strikedetail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.strikedetail'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tooltype',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.tooltype'),
        ),
        migrations.AlterField(
            model_name='strike',
            name='StrikePic',
            field=models.FileField(upload_to='strikes/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='strike',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strikedetail',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='strikedetail',
            name='Weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tool',
            name='QTY',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tooltype',
            name='Name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4, 'Tool minimum length is 4 characters')]),
        ),
    ]
