# Generated by Django 3.2.5 on 2021-08-10 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_member_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='MobileNo',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(500000000, 'Please Enter 9 Numbers.'), django.core.validators.MaxValueValidator(599999999, 'Please Enter Less than 10 Numbers.')]),
        ),
    ]
