# Generated by Django 3.2.5 on 2021-07-28 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20210728_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('Saudi', 'Saudi'), ('Egyptian', 'Egyptian'), ('Sudanese', 'Sudanese'), ('Indian', 'Indian'), ('Pakistani', 'Pakistani')], max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='DoB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='ExpSCE',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='National_ID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10, 'Please Enter 10 Numbers.'), django.core.validators.MaxLengthValidator(10, 'Please Enter 10 Numbers.')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='PassportNo',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.nationality'),
        ),
    ]
