# Generated by Django 3.2.5 on 2021-07-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('WarrantyValidation', models.BooleanField(default=True)),
                ('WarrantyDate', models.DateField()),
                ('WarrantyPDF', models.FileField(upload_to='WarrantyFiles/')),
                ('agentcompany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.agentcompany')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('agentcompanies', models.ManyToManyField(to='supplier.AgentCompany')),
            ],
        ),
        migrations.AddField(
            model_name='agentcompany',
            name='manufacturers',
            field=models.ManyToManyField(to='supplier.Manufacturer'),
        ),
    ]
