# Generated by Django 3.2.5 on 2021-08-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='Name_ar',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='Name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
