# Generated by Django 3.2.5 on 2021-07-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='agentcompanies',
            field=models.ManyToManyField(null=True, to='supplier.AgentCompany'),
        ),
    ]
