# Generated by Django 3.2.5 on 2021-07-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_manufacturer_agentcompanies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='agentcompanies',
            field=models.ManyToManyField(to='supplier.AgentCompany'),
        ),
    ]
