# Generated by Django 3.2.5 on 2021-08-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20210804_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentcompany',
            name='manufacturers',
        ),
    ]
