# Generated by Django 3.2.5 on 2021-07-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='Billpdf',
            field=models.FileField(null=True, upload_to='bills/'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='DateofBill',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
