# Generated by Django 3.2.5 on 2021-07-28 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0002_auto_20210726_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costclass',
            name='Title',
            field=models.CharField(choices=[('محروقات', 'محروقات'), ('ايجار', 'ايجار'), ('مواصلات', 'مواصلات'), ('مستهلكات', 'مستهلكات'), ('مصروفات أخرى', 'مصروفات أخرى')], max_length=50),
        ),
        migrations.AlterField(
            model_name='costtype',
            name='Name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(4, 'CostType must be greater than 4 characters')]),
        ),
    ]
