# Generated by Django 3.2.5 on 2021-07-19 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('employees', '0001_initial'),
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('OpenDate', models.DateTimeField(auto_now_add=True)),
                ('CloseDate', models.DateTimeField(blank=True)),
                ('ProblemDesc', models.TextField(max_length=500)),
                ('Rating', models.IntegerField(blank=True, choices=[('Unacceptable', 1), ('Poor', 2), ('Fair', 3), ('Good', 4), ('Excellent', 5)], null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('DeviceAsset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.deviceasset')),
                ('generalsps', models.ManyToManyField(to='spareparts.GeneralSP')),
            ],
        ),
        migrations.CreateModel(
            name='PPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentPPM', models.DateTimeField(auto_now_add=True)),
                ('FuturePPM', models.DateTimeField(blank=True, null=True)),
                ('DeviceAsset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.deviceasset')),
            ],
        ),
        migrations.CreateModel(
            name='roleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Leader', 'Leader'), ('Member', 'Member')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PPMCreate',
            fields=[
                ('ppm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.ppm')),
            ],
            bases=(django.views.generic.edit.CreateView, 'tasks.ppm'),
        ),
        migrations.CreateModel(
            name='PPMRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.member')),
                ('ppm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ppm')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.rolename')),
            ],
        ),
        migrations.AddField(
            model_name='ppm',
            name='members',
            field=models.ManyToManyField(through='tasks.PPMRole', to='employees.Member'),
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joborder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.joborder')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.member')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.rolename')),
            ],
        ),
        migrations.AddField(
            model_name='joborder',
            name='members',
            field=models.ManyToManyField(through='tasks.JobRole', to='employees.Member'),
        ),
    ]
