# Generated by Django 3.2.5 on 2021-07-29 22:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spareparts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(10, 'Name Must be 10 characters.')])),
                ('OpenDate', models.DateTimeField(blank=True, null=True)),
                ('CloseDate', models.DateTimeField(blank=True, null=True)),
                ('ProblemDesc', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(20, 'Name Must be 20 characters.')])),
                ('Rating', models.IntegerField(blank=True, choices=[('Unacceptable', 1), ('Poor', 2), ('Fair', 3), ('Good', 4), ('Excellent', 5)], null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('deviceasset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.deviceasset')),
                ('generalsps', models.ManyToManyField(to='spareparts.GeneralSP')),
            ],
        ),
        migrations.CreateModel(
            name='PPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentPPM', models.DateTimeField(blank=True, null=True)),
                ('FuturePPM', models.DateTimeField(blank=True, null=True)),
                ('deviceAsset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.deviceasset')),
            ],
        ),
        migrations.CreateModel(
            name='roleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('Leader', 'Leader'), ('Member', 'Member')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PPMCreate',
            fields=[
                ('ppm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.ppm')),
            ],
            bases=(django.views.generic.edit.CreateView, 'tasks.ppm'),
        ),
        migrations.CreateModel(
            name='PPMRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ppm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ppm')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.rolename')),
            ],
        ),
        migrations.AddField(
            model_name='ppm',
            name='members',
            field=models.ManyToManyField(through='tasks.PPMRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joborder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.joborder')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.rolename')),
            ],
        ),
        migrations.AddField(
            model_name='joborder',
            name='members',
            field=models.ManyToManyField(through='tasks.JobRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
