# Generated by Django 3.2.5 on 2021-08-01 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='ProblemDesc',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(20, 'Problem description Must be 20 characters.')]),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='Title',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(10, 'Title Must be 10 characters.')]),
        ),
    ]
