# Generated by Django 3.2.5 on 2021-08-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210730_0145'),
        ('tasks', '0002_auto_20210801_0928'),
    ]

    operations = [
    ]
