# Generated by Django 3.2.5 on 2021-07-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('موجود', 'موجود')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Details', models.TextField(max_length=500)),
                ('PurQTY', models.IntegerField(default=0)),
                ('StbyQTY', models.IntegerField(default=0)),
                ('InstallQTY', models.IntegerField(default=0)),
                ('Purchase_Period', models.IntegerField(blank=True, null=True)),
                ('GeneralSP_PDF', models.FileField(upload_to='')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Notes', models.TextField(blank=True, max_length=500, null=True)),
                ('spstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spareparts.spstatus')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Details', models.CharField(max_length=500)),
                ('PurQTY', models.IntegerField(default=0)),
                ('StbyQTY', models.IntegerField(default=0)),
                ('InstallQTY', models.IntegerField(default=0)),
                ('Purchase_Period', models.IntegerField(blank=True, null=True)),
                ('GeneralSP_PDF', models.FileField(upload_to='')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Notes', models.TextField(blank=True, max_length=500, null=True)),
                ('spstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spareparts.spstatus')),
            ],
        ),
    ]
