# Generated by Django 3.2.5 on 2021-07-26 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210726_0801'),
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.model'),
        ),
    ]
